### PR TITLE
Add mark 'no_default_loop'

### PR DESCRIPTION
**Pull request by masipcat**
Hi,
First of all, the library is great! :) It worked on almost all tests without changing a line of code. 

We have some non-async tests that manage the loop themselves (with `loop = asyncio.get_event_loop` and `loop.close()`). The problem is that after the running the test, the global loop is closed and all the remaining tests fail.

As a workaround, I added the marker `no_default_loop` that "hides" loop to prevent being closed in the test.

I'm open to other approaches.

Thank you

### CODE REVIEW

**Comment by delfick** [comment]
Hi!

I'm glad this library is useful :)

As for your problem, I think I have a better solution. My problem with yours is I want to use marks as little as possible. Also it kinda breaks a little if you have module or session level fixtures that want to use this custom loop, because any futures made in those will be on the wrong event loop.

My solution is instead of just having one loop in alt-pytest-asyncio, I have some kind of stacks of loops as such and so in a fixture you can add a new loop to the stack and then do something like:

```
@pytest.fixture
def custom_loop(alt_loops):
    with alt_loop.add_loop() as loop:
        yield loop

@pytest.fixture()
async def my_future(custom_loop):
    return asyncio.Future()

def test_things(custom_loop, my_future):
    async def blah():
        await do_something(my_future)
        assert (await my_future) == "value"

    custom_loop.run_until_complete(blah())
```

The bad news is I won't have time to make that work right now (maybe this weekend or in the quiet time around christmas) and ensure it does what I think it can 

In the meantime, we can ignore fixtures and you could have in your code:

```
from alt_pytest_asyncio.plugin import cancel_all_tasks

class CustomLoopCM:
    def __init__(self):
        self.tasks = []

    def __enter__(self):
        self._original_loop = asyncio.get_event_loop()
        self.loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self.loop)
        return self.loop

    def __exit__(self, exc_typ, exc, tb):
        try:
            if hasattr(self, "loop"):
                cancel_all_tasks(self.loop, ignore_errors_from_tasks=self.tasks)
                self.loop.close()
        finally:
            if hasattr(self, "_original_loop"):
                asyncio.set_event_loop(self._original_loop)

    def run_until_complete(self, coro):
        if not hasattr(self, "loop"):
            raise Exception(
                "Cannot use run_until_complete on CustomLoopCM outside of using it as a context manager"
            )

        task = self.loop.create_task(coro)

        # Add the task so that when we cancel all tasks before closing the loop
        # We don't complain about errors in this particular task
        # As we get the errors risen to the caller via run_until_complete
        self.tasks.append(task)

        return self.loop.run_until_complete(task)

```

and then do something like

```
def test_example():
    with CusomLoopCM() as loop:
        my_future = asyncio.Future()

        async def blah():
            await do_something(my_future)
            assert (await my_future) == "value"

        loop.run_until_complete(blah())
```
    
 And I'll let you know when I have a solution inside alt-pytest-asyncio itself (either stack idea if I can make it work, or a version of the above context manager).

**Comment by masipcat** [comment]
Thank you for your answer.

I'm not sure about the context manager solution, because this will only change the loop in the test, but no in the fixtures, for example. 

A real-case example test that motivates this PR (we are testing a "Command" that creates, executes and closes the loop in `run_command`):
https://github.com/plone/guillotina/pull/788/files#diff-943174991a0a95675f70c84de5d1b32bL20-L35

I think that would be great to be able to "disable" alt-pytest-asyncio in specific tests. In that case, the user would be responsible for running the loop and everything.

**Comment by delfick** [comment]
So I had a look and it seems your solution doesn't change the event loop for fixtures. With your code (and setting a new event loop instead of just None)

I wrote

```
def print_loop(c, loop):
    print(c, id(loop))


@pytest.fixture()
def fix():
    print_loop("d", asyncio.get_event_loop())


@pytest.fixture()
def fix2():
    print_loop("e", asyncio.get_event_loop())
    yield
    print_loop("e2", asyncio.get_event_loop())


@pytest.fixture()
async def fix3():
    print_loop("f", asyncio.get_event_loop())


@pytest.fixture()
async def fix4():
    print_loop("g", asyncio.get_event_loop())
    yield
    print_loop("g2", asyncio.get_event_loop())


async def test_a(fix, fix2, fix3, fix4):
    print_loop("a", asyncio.get_event_loop())


class TestB:
    # This gets uncommented instead of the mark for the loop to also be in fixtures
    # @pytest.fixture(autouse=True)
    # def alt_loop(self):
    #     with CustomLoopCM() as cm:
    #         yield cm

    @pytest.mark.no_default_loop
    def test_b(self, fix, fix2, fix3, fix4):
        print_loop("b", asyncio.get_event_loop())


async def test_c(fix, fix2, fix3, fix4):
    print_loop("c", asyncio.get_event_loop())

```

and ran it with -s and got 

```
d 4400126720
e 4400126720
f 4400126720
g 4400126720
a 4400126720
.g2 4400126720
e2 4400126720
d 4400126720
e 4400126720
f 4400126720
g 4400126720
b 4414203776
.g2 4400126720
e2 4400126720
d 4400126720
e 4400126720
f 4400126720
g 4400126720
c 4400126720
.g2 4400126720
```

The only one with a different loop is the test with the mark, and not the fixtures it uses.

Whereas if you remove the mark and uncomment the context manager (plus some minor changes to alt_pytest_asyncio) you get

```
d 4408921168
e 4408921168
f 4408921168
g 4408921168
a 4408921168
.g2 4408921168
e2 4408921168
d 4421431592
e 4421431592
f 4421431592
g 4421431592
b 4421431592
.g2 4421431592
e2 4421431592
d 4408921168
e 4408921168
f 4408921168
g 4408921168
c 4408921168
.g2 4408921168
e2 4408921168
```

Which shows all the fixtures for test_b using the new event loop.

Doing it with fixtures also means you can have it in module and class scoped fixtures as well, otherwise those would use the old loop before it gets to test level fixtures.

Are you able to test with this branch here: https://github.com/delfick/alt-pytest-asyncio/compare/overrideloop

Usage for you might look like:

```
from alt_pytest_asyncio.plugin import OverrideLoop

@pytest.fixture(scope="module", autouse=True)
def custom_loop():
    with OverrideLoop(new_loop=False):
        yield

def test_my_loop():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop()
    loop.run_until_complete(things())
    loop.close()
```

Or if you want OverrideLoop to make the loop for you:

```
from alt_pytest_asyncio.plugin import OverrideLoop

@pytest.fixture(scope="module", autouse=True)
def custom_loop():
    with OverrideLoop() as loop:
        # loop at this point is the OverrideLoop object
        # it has it's own run_until_complete that ensures if your test fails
        # you don't get a "unhandled exception during shutdown" error
        # when it cancels all the tasks before closing the loop
        # The asyncio loop itself is the loop property on this object
        yield loop

def test_my_loop(custom_loop):
    custom_loop.run_until_complete(things())
```

Do tell me if this works :)

**Comment by masipcat** [comment]
Thank you very much! I'll give it a try later today

**Comment by delfick** [comment]
I merged my branch and release 0.5.2

**Pull request closed without merging**
