### PR TITLE
Fix license in pyproject.toml

### LINKED ISSUE #14: Missing MIT license in PIP index
PIP index entry doesn't contain valid ``License`` entry.

## Reproduction

1. Install ``alt-pytest-asyncio`` at Ubuntu 20.04:
    ```
    pip install alt-pytest-asyncio
    ```
2. Print ``alt-pytest-asyncio`` license
    ```
    pip show alt-pytest-asyncio
    ```
## Expected result

```
Name: alt-pytest-asyncio
Version: 0.7.0
Summary: Alternative pytest plugin to pytest-asyncio
Home-page: 
Author: 
Author-email: Stephen Moore <delfick755@gmail.com>
License: MIT #<--- MIT SHOULD be HERE
```
## Actual result
```
Name: alt-pytest-asyncio
Version: 0.7.0
Summary: Alternative pytest plugin to pytest-asyncio
Home-page: 
Author: 
Author-email: Stephen Moore <delfick755@gmail.com>
License:       #<--- MIT SHOULD be HERE
```

Also PyPi page in Meta section doesn't display MIT license.

### PR DESCRIPTION
**Pull request by piotrm-nvidia**
Fixes #14

### CODE REVIEW

**Comment by delfick** [comment]
Thanks!

Though this suggests it should already work https://hatch.pypa.io/latest/config/metadata/#__tabbed_10_1

I hopefully will find time on the weekend to look a bit further.

**Comment by delfick** [comment]
hmm, typical python packaging ecosystem, https://github.com/pypa/hatch/issues/665

**Comment by piotrm-nvidia** [comment]
Can you please release new version of ``alt-pytest-asyncio`` on Monday? I will send you a box full of Polish sweets from Warsaw to your home address.

**Comment by delfick** [comment]
release fixed :)

> I will send you a box full of Polish sweets from Warsaw to your home address.

That's not necessary, thanks though!

**Comment by piotrm-nvidia** [comment]
THX. Have a nice weekend.

**Pull request merged**
